---
- name: Create the wg network
  community.general.docker_network:
    name: wg_network
    ipam_config:
      - subnet: "{{ docker_subnet }}"
        gateway: "{{ docker_subnet_prefix }}.1"
        iprange: "{{ docker_subnet }}"
