---
- name: Restart authelia
  community.general.docker_container:
    name: authelia
    restart: yes

- name: Restart bunkerweb
  community.general.docker_container:
    name: bunkerweb
    restart: yes

- Enable and reload ufw
  community.general.ufw:
    state: enabled