---
- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present

- name: Enable UFW logging
  community.general.ufw:
    # yamllint disable-line
    logging: on

- name: Configure UFW
  block:
    - name: Reset all rules
      community.general.ufw:
        state: reset

    - name: Allow the defined ports
      community.general.ufw:
        rule: allow
        proto: "{{ item.proto }}"
        port: "{{ item.port }}"
      with_items:
        - "{{ firewall_ports }}"

    - name: Deny everything else and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
  rescue:
    - name: Grant SSH access to prevent lockout
      community.general.ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: "tcp"

    - name: Deny everything else and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
        
- name: Template the UFW after.rules
  ansible.builtin.blockinfile:
    content: "{{ lookup('template', 'templates/ufw/after.rules.j2') }}"
    insertbefore: "COMMIT"
    dest: /etc/ufw/after.rules
  notify: 
    - UFW enable